import { ArrowRight, BadgeCheck, Building2, CheckCircle2, Hammer, MapPinned, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import Link from 'next/link';
import { Header } from '@/components/site/header'; import { Footer } from '@/components/site/footer'; import { SearchBox } from '@/components/site/search-box'; import { activeRegions, trades } from '@/data/catalog'; import { directorySeed, directoryStats } from '@/data/directory'; import { ListingCard } from '@/components/site/listing-card';
const featuredBusinesses = trades.map((trade) => directorySeed.find((business) => business.region === 'pensacola-fl' && business.trade === trade.slug)).filter((business) => business !== undefined).slice(0, 6);
export default function Home(){return <><Header/><main>
 <section id="find" className="relative scroll-mt-20 overflow-hidden bg-[#eef3f8] px-5 py-16 sm:px-8 sm:py-24"><div className="pointer-events-none absolute inset-0 opacity-40 [background-image:radial-gradient(circle_at_1px_1px,#91a4b7_1px,transparent_0)] [background-size:30px_30px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.08fr_.92fr]">
  <div><div className="inline-flex items-center gap-2 rounded-full border border-[#bed0df] bg-white px-3 py-1.5 text-xs font-extrabold uppercase tracking-[.12em] text-[#35516d]"><MapPinned className="size-3.5 text-[#ec7d2c]"/>Local help, clearly organized</div><h1 className="mt-6 max-w-3xl text-[clamp(3rem,7vw,6.2rem)] font-black leading-[.9] tracking-[-.065em] text-[#142c4c]">Who knows<br/>a <span className="text-[#ec7d2c]">pro?</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Find the right local business for the job. Search by category and region, compare useful details, and contact a provider directly.</p><div className="mt-8 max-w-3xl"><SearchBox/></div><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold text-slate-500"><span className="flex items-center gap-2"><BadgeCheck className="size-4 text-[#27715c]"/>Claimed business profiles</span><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-[#27715c]"/>Clear sponsored labels</span></div></div>
  <div className="relative hidden min-h-[480px] lg:block"><div className="absolute inset-8 rotate-3 rounded-[2.5rem] bg-[#142c4c]"/><div className="absolute inset-0 -rotate-2 rounded-[2.5rem] border border-slate-200 bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><span className="text-sm font-black uppercase tracking-widest text-[#ec7d2c]">Browse near Pensacola</span><Sparkles className="size-5 text-[#ec7d2c]"/></div><div className="mt-7 grid grid-cols-2 gap-3">{trades.slice(0,8).map((t,i)=><a key={t.slug} href={`/pensacola-fl/${t.slug}`} className={`rounded-2xl p-4 transition hover:-translate-y-1 ${i===0?'col-span-2 bg-[#ec7d2c] text-white':'bg-[#eef3f8] text-[#142c4c]'}`}><Wrench className="size-5"/><span className="mt-5 block font-extrabold">{t.name}</span><span className={`mt-1 block text-xs ${i===0?'text-white/75':'text-slate-500'}`}>Browse local providers</span></a>)}</div></div></div>
 </div></section>
 <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Local directory</p><h2 className="section-title">Pros for every kind of project</h2><p className="mt-3 max-w-2xl text-slate-600">Browse {directoryStats.categories} service categories across {directoryStats.cities} active cities. New listings are added as local businesses claim their profiles.</p></div><a className="font-extrabold text-[#d96c20]" href={`/pensacola-fl/${trades[0].slug}`}>Start browsing <ArrowRight className="ml-1 inline size-4"/></a></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{featuredBusinesses.map(b=><ListingCard key={b.id} business={{...b,phone:null,logo_url:null,photo_urls:'[]',owner_email:null,tier:'free',approved:1,stripe_customer_id:null,stripe_subscription_id:null}}/>)}</div></section>
 <section id="regions" className="scroll-mt-20 border-y border-slate-200 bg-[#f5f7fa]"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="eyebrow">Built to expand</p><h2 className="section-title">Browse by region, then by category</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{activeRegions.map((r)=><a key={r.slug} href={`/${r.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 hover:border-[#ec7d2c]"><span className="flex items-center justify-between font-extrabold text-[#142c4c]">{r.name}<ArrowRight className="size-4 transition group-hover:translate-x-1"/></span><span className="mt-3 block text-sm text-slate-500">View all {trades.length} categories</span></a>)}</div></div></section>
 <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="grid gap-5 md:grid-cols-3">{[[Hammer,'Find the right category','Start with the work or local shop you need: roofing, pools, plumbing, trading cards, and more.'],[Building2,'Compare local businesses','See service areas, specialties, photos, websites, and business contact details in one place.'],[CheckCircle2,'Businesses manage profiles','Verified owners can update their profile and choose enhanced or sponsored placement.']].map(([Icon,title,copy])=>{const I=Icon as typeof Hammer;return <div key={title as string} className="rounded-2xl border border-slate-200 p-6"><I className="size-6 text-[#ec7d2c]"/><h3 className="mt-6 text-xl font-extrabold text-[#142c4c]">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy as string}</p></div>})}</div></section>
 <section className="bg-[#ec7d2c] px-5 py-14 text-[#142c4c] sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-widest">Own a service business?</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Claim your profile and make it yours.</h2></div><Link href="/claim" className="rounded-xl bg-[#142c4c] px-6 py-3.5 font-extrabold text-white">Claim your business <ArrowRight className="ml-1 inline size-4"/></Link></div></section>
 </main><Footer/></>}
