export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS businesses (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    main_slug TEXT,
    region TEXT NOT NULL,
    trade TEXT NOT NULL,
    location TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    website TEXT NOT NULL,
    source_url TEXT,
    source_verified_at TEXT,
    public_email TEXT,
    email_source_url TEXT,
    email_verified_at TEXT,
    phone TEXT,
    address TEXT,
    service_area TEXT,
    hours TEXT,
    specialties TEXT,
    year_founded INTEGER,
    license_number TEXT,
    logo_url TEXT,
    photo_urls TEXT NOT NULL DEFAULT '[]',
    owner_email TEXT,
    tier TEXT NOT NULL DEFAULT 'free',
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT,
    approved INTEGER NOT NULL DEFAULT 0,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_slug ON businesses (slug)`,
  `CREATE INDEX IF NOT EXISTS idx_businesses_main_slug ON businesses (main_slug)`,
  `CREATE INDEX IF NOT EXISTS idx_businesses_region_trade ON businesses (region, trade)`,
  `CREATE TABLE IF NOT EXISTS claims (
    id TEXT PRIMARY KEY NOT NULL,
    business_id TEXT NOT NULL,
    email TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    token_hash TEXT,
    expires_at INTEGER,
    requested_plan TEXT,
    requested_region TEXT,
    requested_trade TEXT,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_claims_business_id ON claims (business_id)`,
  `CREATE INDEX IF NOT EXISTS idx_claims_token_hash ON claims (token_hash)`,
  `CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY NOT NULL,
    business_id TEXT NOT NULL,
    email TEXT NOT NULL,
    expires_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_business_id ON sessions (business_id)`,
  `CREATE TABLE IF NOT EXISTS webhooks (
    id TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS directory_seed_versions (
    id TEXT PRIMARY KEY NOT NULL,
    version TEXT NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS leads (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    zip TEXT NOT NULL,
    job_description TEXT NOT NULL,
    preferred_contact_method TEXT NOT NULL,
    region TEXT NOT NULL,
    trade TEXT NOT NULL,
    page_url TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    routed INTEGER NOT NULL DEFAULT 0,
    routed_business_id TEXT,
    routed_business_slug TEXT,
    routed_at INTEGER,
    owner_notification_status TEXT NOT NULL DEFAULT 'pending',
    business_notification_status TEXT NOT NULL DEFAULT 'not_applicable',
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_leads_region_trade_created ON leads (region, trade, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_ip_created ON leads (ip_address, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_routed_business ON leads (routed_business_slug, created_at)`,
  `CREATE TABLE IF NOT EXISTS featured_slots (
    id TEXT PRIMARY KEY NOT NULL,
    region TEXT NOT NULL,
    trade TEXT NOT NULL,
    business_id TEXT NOT NULL,
    business_slug TEXT NOT NULL,
    stripe_checkout_session_id TEXT,
    stripe_subscription_id TEXT,
    status TEXT NOT NULL,
    reserved_until INTEGER,
    activated_at INTEGER,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_featured_slots_page ON featured_slots (region, trade)`,
  `CREATE INDEX IF NOT EXISTS idx_featured_slots_business ON featured_slots (business_slug)`,
  `CREATE INDEX IF NOT EXISTS idx_featured_slots_subscription ON featured_slots (stripe_subscription_id)`,
  `CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY NOT NULL,
    business_id TEXT NOT NULL,
    business_slug TEXT NOT NULL,
    stripe_customer_id TEXT NOT NULL,
    plan TEXT NOT NULL,
    status TEXT NOT NULL,
    featured_region TEXT,
    featured_trade TEXT,
    cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
    current_period_end INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_subscriptions_business ON subscriptions (business_slug)`,
  `CREATE INDEX IF NOT EXISTS idx_subscriptions_customer ON subscriptions (stripe_customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions (status)`,
  `CREATE TABLE IF NOT EXISTS profile_views (
    id TEXT PRIMARY KEY NOT NULL,
    business_slug TEXT NOT NULL,
    viewer_hash TEXT NOT NULL,
    viewed_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_profile_views_business_date ON profile_views (business_slug, viewed_at)`,
  `CREATE TABLE IF NOT EXISTS admin_login_tokens (
    token_hash TEXT PRIMARY KEY NOT NULL,
    email TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    used_at INTEGER,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_admin_login_tokens_email ON admin_login_tokens (email, created_at)`,
  `CREATE TABLE IF NOT EXISTS admin_sessions (
    token_hash TEXT PRIMARY KEY NOT NULL,
    email TEXT NOT NULL,
    expires_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_admin_sessions_email ON admin_sessions (email)`,
] as const;

export const additiveColumns = {
  businesses: [
    ['email_source_url', 'TEXT'],
    ['email_verified_at', 'TEXT'],
  ],
  claims: [
    ['requested_plan', 'TEXT'],
    ['requested_region', 'TEXT'],
    ['requested_trade', 'TEXT'],
  ],
} as const;
